server:
  port: ${PORT:8080}
infinispan:
  embedded:
    config-xml: config/infinispan.xml
spring:
  cache:
    type: INFINISPAN
jgroups.dns.query: ${JROUPS_DNS_QUERY:infinispan-cluster.develop.svc.cluster.local}
#logging:
#  level:
#    org.infinispan: TRACE